### ISSUE TITLE
Deploy app in Openshift

### ISSUE THREAD

**Issue by aureamunoz** [snowdrop/spring-quarkus-fruits#1]
We would like to deploy this applications `[Spring Boot crud example](https://github.com/snowdrop/crud-example)` and `Quarkus crud example` on Openshift in order to showcase during the Red Hat Forum a comparison between the start-up time and memory footprint in both.

To do with @jparrill  and @mvazquezc, the others speakers.

**Comment by mvazquezc** [comment]
Created container image for Quarkus Native and Quarkus Jvm. Created Manifests for deploy those images.

https://github.com/snowdrop/spring-quarkus-fruits/pull/2

**Comment by aureamunoz** [comment]
Thank you Mario!!

**Comment by aureamunoz** [comment]
I finally pushed the image @mvazquezc, @jparrill 
https://quay.io/repository/amunozhe/spring-quarkus-fruits
https://quay.io/repository/amunozhe/spring-boot-crud

**Comment by mvazquezc** [comment]
@aureamunoz  It seems the repositories are private, could you make them public?

**Comment by aureamunoz** [comment]
done! Let me know if it's ok @mvazquezc

**Comment by mvazquezc** [comment]
@aureamunoz I can access now, thanks!

**Comment by cmoulliard** [comment]
- What is the status : done, still under development, .... ? 
- Is it documented under a `README.md` file how to play with the demo (something similar to what we did with Giorgios here : https://github.com/snowdrop/demo-sidebyside/blob/master/README.md) ?
@aureamunoz

**Comment by mvazquezc** [comment]
@cmoulliard The files can be accessed here: https://github.com/snowdrop/spring-quarkus-fruits/tree/master/k8s

We still need to publish the files for deploying the spring boot application, at the moment we only have the quarkus native and quarkus jvm apps published.
